name: Maven Build and Publish Jar

# 3(a) — Trigger: executa sempre que há push na branch principal
on:
  push:
    branches:
      - main

# Define o job principal
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 3(b) — Faz checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura o ambiente Java (versão 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 3(c) — Executa build Maven
      - name: Build with Maven
        run: mvn -B clean package

      # 3(d) — Publica o ficheiro JAR como artefacto
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

